### ISSUE TITLE
crash with put/match

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2269]
Repro is with `zq` commit `49c5a2f2`.

```
zq -z "put t=match(*=10.1.1.3)" in.zson
```

in.zson:

```
{v:[10.1.1.2]}
{v:[10.1.1.2,10.1.1.3]}
```

Panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
runtime/debug.Stack(0xc0002a1b10, 0x191fd9d, 0x2)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/brimsec/zq/zqe.RecoverError(0x182b4a0, 0x1ed4290, 0x1ed4290, 0x3)
	/Users/phil/work/zq/zqe/error.go:163 +0x26
github.com/brimsec/zq/driver.(*mux).safeGet.func1(0xc000337f70)
	/Users/phil/work/zq/driver/mux.go:49 +0x48
panic(0x182b4a0, 0x1ed4290)
	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
github.com/brimsec/zq/zng.(*TypeRecord).ZSON(0xc000337540, 0xc000337568, 0x1ea5040)
	/Users/phil/work/zq/zng/record.go:148 +0x2d4
github.com/brimsec/zq/zson.(*Context).LookupTypeRecord(0xc00047fea0, 0xc00031c100, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/zson/context.go:101 +0x1e5
github.com/brimsec/zq/proc/put.(*Proc).deriveRecordSteps(0xc00031a120, 0xc000337b18, 0x0, 0x0, 0xc00030c260, 0x1, 0x1, 0xc000312240, 0x1, 0x1, ...)
	/Users/phil/work/zq/proc/put/put.go:309 +0x56d
github.com/brimsec/zq/proc/put.(*Proc).deriveSteps(0xc00031a120, 0xc000312510, 0xc000312240, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/proc/put/put.go:224 +0x21b
github.com/brimsec/zq/proc/put.(*Proc).lookupRule(0xc00031a120, 0xc000312510, 0xc000312240, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/proc/put/put.go:336 +0x145
github.com/brimsec/zq/proc/put.(*Proc).put(0xc00031a120, 0xc000314280, 0xc000314280, 0xc00030e260, 0x0)
	/Users/phil/work/zq/proc/put/put.go:352 +0xba
github.com/brimsec/zq/proc/put.(*Proc).Pull(0xc00031a120, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/put/put.go:371 +0x15f
github.com/brimsec/zq/driver.(*mux).safeGet(0xc00030c0e0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc00030c0e0)
	/Users/phil/work/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:98 +0x5d
```

**Comment by mccanne** [comment]
We no longer have the `*=` pattern but this works now:
```
% cat in.zson
{v:[10.1.1.2]}
{v:[10.1.1.2,10.1.1.3]}
% zq -z "put t:=match(10.1.1.3)" in.zson
{v:[10.1.1.2],t:false}
{v:[10.1.1.2,10.1.1.3],t:true}
```
