### ISSUE TITLE
Compiler crash when Z script references a non-existent alias

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2281]
```
$ echo {} | zq -z "put . = shape({a: zenum})" -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x153e6c6]

goroutine 1 [running]:
github.com/brimsec/zq/zng.(*TypeAlias).ZSON(0x0, 0x1eb0fc8, 0x1)
	/Users/henridf/work/brim/zq/zng/alias.go:47 +0x26
github.com/brimsec/zq/zng.(*TypeRecord).ZSON(0xc00079e6a0, 0xc00079e6c8, 0x1eb0fc8)
	/Users/henridf/work/brim/zq/zng/record.go:148 +0x2e6
github.com/brimsec/zq/zson.(*Context).LookupTypeRecord(0xc000557db0, 0xc00011a0a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/henridf/work/brim/zq/zson/context.go:101 +0x1e5
github.com/brimsec/zq/zson.Analyzer.convertTypeRecord(0xc00079e988, 0xc000557db0, 0xc000595bf0, 0xa808e00, 0xa9fffff, 0xc00079e8c0)
	/Users/henridf/work/brim/zq/zson/analyzer.go:621 +0x1c9
github.com/brimsec/zq/zson.Analyzer.convertType(0xc00079e988, 0xc000557db0, 0x1a96ce0, 0xc000595bf0, 0x20300000000000, 0xc00079e948, 0x10177af, 0xa808e00)
	/Users/henridf/work/brim/zq/zson/analyzer.go:579 +0x6a8
github.com/brimsec/zq/zson.TranslateType(...)
	/Users/henridf/work/brim/zq/zson/zson.go:72
github.com/brimsec/zq/compiler/kernel.compileTypeExpr(0xc0000107b0, 0xc00011a020, 0x192eced, 0x8, 0x1a96ce0, 0xc000595bf0, 0x28, 0x1a73701, 0xaaaaaaaaaaaaaaaa, 0x38)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:453 +0x1a7
github.com/brimsec/zq/compiler/kernel.compileExpr(0xc0000107b0, 0xc00011a020, 0x1a96c40, 0xc00011a000, 0x1a97020, 0x2470d70, 0x0, 0x0)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:86 +0x852
github.com/brimsec/zq/compiler/kernel.compileShaper(0xc0000107b0, 0xc00011a020, 0x1936ba2, 0xc, 0xc0005667f0, 0x5, 0xc000118000, 0x1, 0x1, 0xc000042800, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:381 +0xea
github.com/brimsec/zq/compiler/kernel.compileCall(0xc0000107b0, 0xc00011a020, 0x1936ba2, 0xc, 0xc0005667f0, 0x5, 0xc000118000, 0x1, 0x1, 0xc000000180, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:412 +0x6b0
github.com/brimsec/zq/compiler/kernel.compileExpr(0xc0000107b0, 0xc00011a020, 0x1a96840, 0xc00011c000, 0xc00011e120, 0x10177af, 0xc00005cd80, 0xc000000180)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:82 +0x794
github.com/brimsec/zq/compiler/kernel.CompileAssignment(0xc0000107b0, 0xc00011a020, 0xc00079f1a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa9fffff, 0xc000497180)
	/Users/henridf/work/brim/zq/compiler/kernel/expr.go:300 +0xc8
github.com/brimsec/zq/compiler/kernel.compileAssignments(0xc000692360, 0x1, 0x1, 0xc0000107b0, 0xc00011a020, 0x203000, 0xac035b0, 0xc00079f2f0, 0x203000, 0x203000)
	/Users/henridf/work/brim/zq/compiler/kernel/proc.go:204 +0x134
github.com/brimsec/zq/compiler/kernel.compileProc(0x0, 0x1a96a00, 0xc00011e030, 0xc00011e0f0, 0xc00011a020, 0x1a9f360, 0xc000118040, 0x10177af, 0xa809100, 0x20300000000000, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/proc.go:147 +0x156e
github.com/brimsec/zq/compiler/kernel.Compile(0x0, 0x1a96a00, 0xc00011e030, 0xc00011e0f0, 0xc00011a020, 0xc000118020, 0x1, 0x1, 0xc00079f6f8, 0x101a9fe, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/proc.go:381 +0x725
github.com/brimsec/zq/compiler/kernel.compileSequential(0x0, 0xc000118010, 0x1, 0x1, 0xc00011e0f0, 0xc00011a020, 0xc000118020, 0x1, 0x1, 0x8, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/proc.go:242 +0xc5
github.com/brimsec/zq/compiler/kernel.Compile(0x0, 0x1a96b20, 0xc00011e060, 0xc00011e0f0, 0xc00011a020, 0xc000118020, 0x1, 0x1, 0x100fff8, 0x30, ...)
	/Users/henridf/work/brim/zq/compiler/kernel/proc.go:332 +0x8e5
github.com/brimsec/zq/compiler.(*Runtime).Compile(0xc00011e0c0, 0x0, 0xc00011e0f0, 0xc000118020, 0x1, 0x1, 0x0, 0x7fffffffffffffff)
	/Users/henridf/work/brim/zq/compiler/compiler.go:158 +0x89
github.com/brimsec/zq/driver.compile(0x1aa7ba0, 0xc00069e040, 0x1a96b20, 0xc000595cb0, 0xc0000107b0, 0xc00079fa90, 0x1, 0x1, 0x0, 0xc0006a0120, ...)
	/Users/henridf/work/brim/zq/driver/compile.go:88 +0x57a
github.com/brimsec/zq/driver.Run(0x1aa81a0, 0xc000692180, 0x1aa7ea0, 0xc0006922d0, 0x1a96b20, 0xc000595cb0, 0xc0000107b0, 0x1a97540, 0xc000692150, 0x0, ...)
	/Users/henridf/work/brim/zq/driver/driver.go:29 +0x145
main.(*Command).Run(0xc0002096c0, 0xc0000320e0, 0x2, 0x2, 0x0, 0x0)
	/Users/henridf/work/brim/zq/cmd/zq/zq.go:192 +0xbb5
github.com/mccanne/charm.(*instance).run(0xc0002ca2c0, 0xc0000320d0, 0x3, 0x3, 0x0, 0x0)
	/Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x293
github.com/mccanne/charm.(*Spec).ExecRoot(0x1f0af60, 0xc0000320d0, 0x3, 0x3, 0xc00019ff78, 0x1007f65, 0xc00008e058, 0x0)
	/Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
	/Users/henridf/work/brim/zq/cmd/zq/main.go:9 +0x85

```

**Comment by mccanne** [comment]
This has been fixed...
```
echo {} | zq -z "put this:=shape({a: zenum})" -
put: a referenced field is missing
{}
```
