### ISSUE TITLE
Crash when passing a TypeExpr to sum()

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2343]
```
$ echo "{}" | zq -z "sum([foo])" -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x153f726]

goroutine 1 [running]:
github.com/brimsec/zq/zng.(*TypeAlias).ZSON(0x0, 0x1564a8f, 0xc000472320)
	/Users/henridf/work/zq/zng/alias.go:47 +0x26
github.com/brimsec/zq/zng.(*TypeArray).ZSON(0xc00019ea98, 0xc000472320, 0xc000467180)
	/Users/henridf/work/zq/zng/array.go:95 +0x38
github.com/brimsec/zq/zson.(*Context).LookupTypeArray(0xc000472320, 0x1aaff68, 0x0, 0x0)
	/Users/henridf/work/zq/zson/context.go:149 +0x8f
github.com/brimsec/zq/zson.Analyzer.convertType(0xc00019ec08, 0xc000472320, 0x1a9b660, 0xc00045cb40, 0xf0000c0004679f0, 0xc00019ec08, 0x100f0bb, 0xc00051c080)
	/Users/henridf/work/zq/zson/analyzer.go:585 +0x3c5
github.com/brimsec/zq/zson.TranslateType(...)
	/Users/henridf/work/zq/zson/zson.go:72
github.com/brimsec/zq/compiler/kernel.compileTypeExpr(0xc000010740, 0x0, 0x191bc4b, 0x8, 0x1a9b660, 0xc00045cb40, 0xc00019eee0, 0x16e6535, 0xc00019f7f0, 0x191f445)
	/Users/henridf/work/zq/compiler/kernel/expr.go:453 +0x1a7
github.com/brimsec/zq/compiler/kernel.compileExpr(0xc000010740, 0x0, 0x1a9b6c0, 0xc000522000, 0x8, 0x8, 0x2c013c8, 0x8)
	/Users/henridf/work/zq/compiler/kernel/expr.go:86 +0x932
github.com/brimsec/zq/compiler/kernel.compileAgg(0xc000010740, 0xc00050c030, 0x191f445, 0xa, 0x1a9b260, 0xc0005121e0, 0x1a9b4a0, 0xc00051c080, 0x100, 0x203000, ...)
	/Users/henridf/work/zq/compiler/kernel/groupby.go:50 +0x385
github.com/brimsec/zq/compiler/kernel.compileAggs(0xc0005121b0, 0x1, 0x1, 0xc00050c030, 0xc000010740, 0x2458e78, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/henridf/work/zq/compiler/kernel/groupby.go:31 +0x18a
github.com/brimsec/zq/compiler/kernel.compileGroupBy(0xc0005122a0, 0xc00050c030, 0x1aa3820, 0xc00050e080, 0xc00051e0c0, 0xc00019f260, 0x1019837, 0x8)
	/Users/henridf/work/zq/compiler/kernel/groupby.go:20 +0xf6
github.com/brimsec/zq/compiler/kernel.compileProc(0x0, 0x1a9b300, 0xc00051e0c0, 0xc0005122a0, 0xc00050c030, 0x1aa3820, 0xc00050e080, 0xc000516000, 0x1, 0xc00019f5b0, ...)
...
```

**Comment by philrz** [comment]
I'm going to save myself the binary search of figuring out precisely which commit addressed this, but I'm happy to say this issue is not present as of `zq` commit dd946d3. Repeating the original repro steps, there's no longer a crash:

```
$ zq -version
Version: v0.29.0-209-gdd946d38

$ echo "{}" | zq -z "sum([foo])" -
{sum:null (null)} (=0)
```
