### ISSUE TITLE
Panic when using generators

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2372]
@henridf reported this issue in a [thread on public Slack](https://brimsec.slack.com/archives/CTSMAK6G7/p1616080915001500). I confess this syntax is new enough that I don't even know what it's doing, but surely we don't want it to panic. Repro is with `zq` commit 5e8385c and the [zq-sample-data](https://github.com/brimsec/zq-sample-data).

```
$ zq -version
Version: v0.29.0-139-g5e8385cb

$ zq -z 'put n=count(select(.).filter(len($)>1))' *
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 68 [running]:
runtime/debug.Stack(0x2da0700, 0x100, 0x2f3ffff)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/brimsec/zq/zqe.RecoverError(0x181e020, 0x1ec5f90, 0x1ec5f90, 0x2da0700)
	/Users/phil/work/zq/zqe/error.go:163 +0x26
github.com/brimsec/zq/driver.(*mux).safeGet.func1(0xc000b1bf70)
	/Users/phil/work/zq/driver/mux.go:49 +0x4b
panic(0x181e020, 0x1ec5f90)
	/usr/local/opt/go/libexec/src/runtime/panic.go:965 +0x1b9
github.com/brimsec/zq/zng.(*TypeRecord).ZSON(0xc000b1b4b8, 0xc000b1b4e0, 0x1e93b50)
	/Users/phil/work/zq/zng/record.go:98 +0x2d4
github.com/brimsec/zq/zson.(*Context).LookupTypeRecord(0xc000412d70, 0xc000796800, 0x1c, 0x20, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/zson/context.go:101 +0x1e5
github.com/brimsec/zq/proc/put.(*Proc).deriveRecordSteps(0xc0007301b0, 0xc000b1ba90, 0x0, 0x0, 0xc0008a8380, 0x1b, 0x1b, 0xc000275800, 0x1, 0x1, ...)
	/Users/phil/work/zq/proc/put/put.go:309 +0x536
github.com/brimsec/zq/proc/put.(*Proc).deriveSteps(0xc0007301b0, 0xc0008d8180, 0xc000275800, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/proc/put/put.go:224 +0x233
github.com/brimsec/zq/proc/put.(*Proc).lookupRule(0xc0007301b0, 0xc0008d8180, 0xc000275800, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/proc/put/put.go:336 +0x15e
github.com/brimsec/zq/proc/put.(*Proc).put(0xc0007301b0, 0xc0008e93b0, 0xc0008e93b0, 0xc0007a2e00, 0x0)
	/Users/phil/work/zq/proc/put/put.go:352 +0xe5
github.com/brimsec/zq/proc/put.(*Proc).Pull(0xc0007301b0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/put/put.go:371 +0x165
github.com/brimsec/zq/driver.(*mux).safeGet(0xc00015ae20, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc00015ae20)
	/Users/phil/work/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:98 +0x5d
```

As he later observed when working around the crash:

> oh, i see, the crash only happens when some fields are non-string:
> 
> ```
> $ echo '{"a": "", "b": "foo"}' | zq -f ndjson 'put n=count(select(.).filter(len($)>1))' -
> {"a":"","b":"foo","nskills":1}
> $ echo '{"a": "", "b": "foo", c: 1}' | zq -f ndjson 'put n=count(select(.).filter(len($)>1))' -
> ```

**Comment by philrz** [comment]
I'm going to save myself the binary search of figuring out precisely which commit addressed this, but I'm happy to say this issue is not present as of `zq` commit [dd946d3](https://github.com/brimdata/zed/commit/dd946d3890f4feddb87d9d8d9d175e1ef235604a). Repeating the original repro steps, we now see a `len: bad argument` message in the presence of non-string fields rather than a panic.

```
$ zq -version
Version: v0.29.0-209-gdd946d38

$ echo '{"a": "", "b": "foo", c: 1}' | zq -f ndjson 'put n=count(select(.).filter(len($)>1))' -
len: bad argument
{"a":"","b":"foo","c":1}
```
