### ISSUE TITLE
Don't automatically fuse for CSV output

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2402]
After some time working with the changes from #1908, consensus is that the "auto-fuse" behavior is undesirable. Per a team discussion on March 23, 2021, the `-csvfuse` option will be removed, a single pass will be made through the data when outputting as CSV, and if the output is halted due to the presence of multiple types, the user would have the option to append a `| fuse` to their Z and re-run.

Right now here's how the error message would look in that case (running `zq` commit 75e8906 with the [zq-sample-data](https://github.com/brimsec/zq-sample-data)):

```
$ zq -f csv -csvfuse=false *
_path,ts,peer,mem,pkts_proc,bytes_recv,pkts_dropped,pkts_link,pkt_lag,events_proc,events_queued,active_tcp_conns,active_udp_conns,active_icmp_conns,tcp_conns,udp_conns,icmp_conns,timers,active_timers,files,active_files,dns_requests,active_dns_requests,reassem_tcp_size,reassem_file_size,reassem_frag_size,reassem_unknown_size
stats,2018-03-24T17:15:20.600725Z,zeek,74,26,29375,,,,404,11,1,0,0,1,0,0,36,32,0,0,0,0,1528,0,0,0
csv output requires uniform records but different types encountered
```

If I could make a plea to whoever implements this issue: Could we add _some_ mention of the `fuse` processor in this output? Perhaps a parenthetical statement like `(consider using 'fuse')`?

**Comment by philrz** [comment]
I'm not sure if this is the bug that @mccanne already ran into, but while playing with the new SQL support I triggered a panic that's unique to outputting CSV. Using `zq` commit 28a347d and the [fruit sample data](https://github.com/mccanne/fruit):

```
$ zq -z 'SELECT * FROM fruit f ORDER by f.name LIMIT 3' fruit.zson | zq -f csv -
panic: interface conversion: zng.Type is *zng.TypeAlias, not *zng.TypeRecord

goroutine 1 [running]:
github.com/brimsec/zq/expr.createStep(0x1ac9688, 0xc0004925d0, 0x1ac9bc8, 0xc000492b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/expr/shaper.go:130 +0x9f2
github.com/brimsec/zq/expr.createStepRecord(0xc000492600, 0xc000492ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/expr/shaper.go:69 +0x37b
github.com/brimsec/zq/expr.(*Shaper).createShapeSpec(0xc0004a3260, 0xc000492600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/expr/shaper.go:344 +0x15c
github.com/brimsec/zq/expr.(*Shaper).Eval(0xc0004a3260, 0xc000494370, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000492600, 0xc000492600)
	/Users/phil/work/zq/expr/shaper.go:300 +0x3d6
github.com/brimsec/zq/expr.(*Shaper).Apply(0xc0004a3260, 0xc000494370, 0xc000494370, 0x0, 0x0)
	/Users/phil/work/zq/expr/shaper.go:283 +0x6c
github.com/brimsec/zq/proc/fuse.(*Fuser).Read(0xc0004940a0, 0x0, 0x0, 0xb295190)
	/Users/phil/work/zq/proc/fuse/fuser.go:145 +0xd0
github.com/brimsec/zq/zbuf.CopyWithContext(0x1ac9110, 0xc000038088, 0xb295190, 0xc00049a040, 0x1aba040, 0xc0004940a0, 0x0, 0x0)
	/Users/phil/work/zq/zbuf/zbuf.go:59 +0x5b
github.com/brimsec/zq/zbuf.Copy(...)
	/Users/phil/work/zq/zbuf/zbuf.go:71
github.com/brimsec/zq/proc/fuse.(*writeCloser).Close(0xc00048c018, 0xc0003d3620, 0x1ac9378)
	/Users/phil/work/zq/proc/fuse/writer.go:23 +0x91
main.(*Command).Run(0xc000223380, 0xc000032070, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/work/zq/cmd/zq/zq.go:202 +0xa53
github.com/mccanne/charm.(*instance).run(0xc000089440, 0xc000032050, 0x3, 0x3, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x2a2
github.com/mccanne/charm.(*Spec).ExecRoot(0x1f26f80, 0xc000032050, 0x3, 0x3, 0xc00021ff78, 0x1007865, 0xc0000a4058, 0x10014b0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x99
main.main()
	/Users/phil/work/zq/cmd/zq/main.go:9 +0x85
```

However, the problem doesn't occur when we bypass the auto-fuse.

```
$ zq -z 'SELECT * FROM fruit f ORDER by f.name LIMIT 3' fruit.zson | zq -f csv -csvfuse=false -
f
"apple,red,tart"
"banana,yellow,sweet"
"dates,brown,sweet"
```

I decided not to open a separate issue since it sounds like the auto-fuse is not long for this earth.

**Comment by philrz** [comment]
Verified in `zq` commit 79c4047. Now if I attempt to output diverse data as CSV (such as the [Zeek zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-default)), it halts and advises me that `fuse` may be appropriate.

```
zq-sample-data/zeek-default$ zq -f csv *
_path,ts,ts_delta,peer,gaps,acks,percent_lost
capture_loss,2018-03-24T17:30:20.600852Z,900.000127,zeek,1400,1414346,0.098986
capture_loss,2018-03-24T17:36:30.158766Z,369.557914,zeek,919,663314,0.138547
CSV output requires uniform records but multiple types encountered (consider 'fuse')
```

This boosts the priority of addressing brimdata/brim#1530. As of the most recently nightly Brim build, CSV Export is now effectively broken. As a user, if I try to export diverse data, it acts like it succeeded, but the file created looks like:

```
$ cat results.csv 
query error: CSV output requires uniform records but multiple types encountered (consider 'fuse')
```

Thanks @nwt!
