### ISSUE TITLE
SEGV panic when referencing incorrect key names in "zar index create"

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2417]
Repros are with `zar` commit bcf7f34.

While working on the `zar` README updates in #2414, I made a typo that led to a panic (note the `from,to` in the final step... that's the mistake).

```
$ rm -rf /tmp/logs && mkdir /tmp/logs && ZAR_ROOT=/tmp/logs && zar import -s 25MB zng/*.gz
$ zar map -o forward.zng "id.orig_h != null | put from_addr=id.orig_h,to_addr=id.resp_h | count() by from_addr,to_addr"
$ zar map -o reverse.zng "id.orig_h != null | put from_addr=id.resp_h,to_addr=id.orig_h | count() by from_addr,to_addr"
$ zar map -o directed-pairs.zng "count=sum(count) by from_addr,to_addr | sort from_addr,to_addr" forward.zng reverse.zng
$ zar index create -i directed-pairs.zng -o graph.zng -k from,to -z "*"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18c475e]

goroutine 19 [running]:
github.com/brimsec/zq/ppl/lake/index.(*indexer).Write(0xc0005102a0, 0xc0004ec410, 0x0, 0x0)
	/Users/phil/work/zq/ppl/lake/index/writer.go:167 +0x29e
github.com/brimsec/zq/zbuf.CopyWithContext(0x1df14d0, 0xc0000380a0, 0x1dddb80, 0xc0005102a0, 0x2b10fb98, 0xc0004984c0, 0x0, 0xc0005f7358)
	/Users/phil/work/zq/zbuf/zbuf.go:63 +0x8b
github.com/brimsec/zq/zbuf.Copy(...)
	/Users/phil/work/zq/zbuf/zbuf.go:71
github.com/brimsec/zq/ppl/lake/index.(*indexer).start.func1(0xc0005102a0)
	/Users/phil/work/zq/ppl/lake/index/writer.go:147 +0x8e
created by github.com/brimsec/zq/ppl/lake/index.(*indexer).start
	/Users/phil/work/zq/ppl/lake/index/writer.go:146 +0x5c
```

**Comment by mccanne** [comment]
No longer relevant
