### ISSUE TITLE
"zapi new -p" causes "index out of range" error

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2648]
Repro is with `zed` commit aa4170e.

I've got `zed lake serve` running at commit aa4170e and was using `zapi` to create pools in it. The following works as intended:

```
$ zapi new foo
foo: pool created

$ zapi ls
foo
```

However, I've got muscle memory of using `-p` to mention a pool name in many commands. Indeed, this is even mentioned in the `zapi` help output:

```
$ zapi new -h
NAME
    zed api new - create a new pool

USAGE
    new [poolname]

OPTIONS
    -k one or more pool keys to organize data in pool (cannot be changed) (default "ts")
    -order sort order of newly created pool (cannot be changed) (default "desc")
    -S target size of pool data objects, as '10MB' or '4GiB', etc. (default "500MiB")
    
    [api flags]
    -configpath directory to store local configuration and credentials
    -host host[:port] (default "localhost:9867")
    -nofancy disable fancy CLI output (true if stdout is not a tty) (default "false")
    -p pool
...
```

I then made the mistake of actually _using_ it, and that produces a stack trace.

```
$ zapi new -p bar
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/brimdata/zed/cmd/zed/api/new.(*Command).Run(0xc0002a4e70, 0xc000021470, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zed/cmd/zed/api/new/new.go:48 +0x3d5
github.com/brimdata/zed/pkg/charm.path.run(0xc000079a80, 0x3, 0x4, 0xc000021470, 0x0, 0x0, 0xc000079a80, 0x3)
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8f
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x1cf1500, 0xc000021440, 0x4, 0x4, 0x3, 0x3)
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x1e7
main.main()
	/Users/phil/work/zed/cmd/zapi/main.go:23 +0x193
```

**Comment by mattnibs** [comment]
This appears to be fixed in the newest version of zapi:

```
> zapi new -p hi 
"zed api": no such sub-command "new": options are: add commit create delete drop load log ls query squash status
