### ISSUE TITLE
zq hangs on attempted CSV output of ZNG file (deadlock?) (regression at dd7103a)

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2926]
This problem can be reproduced starting with Zed commit dd7103a, and is also present in current Zed tip of main commit 1099f2f.

To reproduce, I concatenate all of the [ZNG-format Zeek zed-sample data](https://github.com/brimdata/zed-sample-data/tree/main/zng) into a single file, then attempt to output it as CSV.

As of Zed commit 09de9ba, this "failed fast" as expected.

```
~/work/zed-sample-data/zng$ zq -version
Version: v0.29.0-323-g09de9bab

~/work/zed-sample-data/zng$ zq * > /tmp/results.zng 

~/work/zed-sample-data/zng$ zq -f csv /tmp/results.zng 
_path,ts,ts_delta,peer,gaps,acks,percent_lost
capture_loss,2018-03-24T17:30:20.600852Z,900.000127,zeek,1400,1414346,0.098986
capture_loss,2018-03-24T17:36:30.158766Z,369.557914,zeek,919,663314,0.138547
CSV output requires uniform records but multiple types encountered (consider 'fuse')
```

However, advancing to the next Zed commit dd7103a, which is associated with #2682 (cc: @nwt), now it hangs. In the attached video, I keep the macOS Activity Monitor open and we can see the `zq` process showing no CPU utilization, which leads me to wonder if it's deadlocked.

https://user-images.githubusercontent.com/5934157/129810010-a0794553-f84f-4aa9-8597-7a32085339b1.mp4

I'm not sure if this helps at all, but when I give up on it and hit Control-`\`, here's what the stack dump looks like:

```
~/work/zed-sample-data/zng$ zq -f csv /tmp/results.zng 
^\SIGQUIT: quit
PC=0x7fff203accde m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x1e29420, 0x1e293e0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:384 +0x39
runtime.semasleep(0xffffffffffffffff, 0xc00004a800)
	/usr/local/opt/go/libexec/src/runtime/os_darwin.go:63 +0x8d
runtime.notesleep(0x1e291d0)
	/usr/local/opt/go/libexec/src/runtime/lock_sema.go:181 +0xdb
runtime.mPark()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1340 +0x39
runtime.stoplockedm()
	/usr/local/opt/go/libexec/src/runtime/proc.go:2495 +0x6e
runtime.schedule()
	/usr/local/opt/go/libexec/src/runtime/proc.go:3103 +0x48c
runtime.park_m(0xc000001c80)
	/usr/local/opt/go/libexec/src/runtime/proc.go:3318 +0x9d
runtime.mcall(0x106ed36)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:327 +0x5b

goroutine 1 [chan receive]:
github.com/brimdata/zed/driver.run.func1(0xc00044eed0, 0xc0004c63c0, 0xc0004c6420)
	/Users/phil/work/zed/driver/driver.go:112 +0x5c
github.com/brimdata/zed/driver.run(0xc00044eed0, 0x1a286f8, 0xc00044ede0, 0xc00010e7e0, 0x0, 0x1a19000, 0xc000262cb0)
	/Users/phil/work/zed/driver/driver.go:172 +0x31c
github.com/brimdata/zed/driver.RunWithFileSystem(0x1a28960, 0xc0002becc0, 0x1a286f8, 0xc00044ede0, 0x1a19720, 0xc00044eea0, 0xc0004465f0, 0x1a1aa00, 0xc00044ecf0, 0x1a29d38, ...)
	/Users/phil/work/zed/driver/driver.go:60 +0x16e
github.com/brimdata/zed/cmd/zed/query.(*Command).Run(0xc0000cb680, 0xc0000331b0, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/work/zed/cmd/zed/query/command.go:173 +0x805
github.com/brimdata/zed/pkg/charm.path.run(0xc0002c8110, 0x2, 0x2, 0xc0000331b0, 0x1, 0x1, 0xc0002c8110, 0x2)
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8f
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x1e1d320, 0xc000033180, 0x4, 0x4, 0x3, 0x3)
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x1e7
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:14 +0x193

goroutine 18 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/opt/go/libexec/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x45

goroutine 19 [select, 1 minutes]:
github.com/brimdata/zed/pkg/signalctx.New.func1(0xc000046f60, 0xc0002becc0, 0xc0002c8120, 0x1a28458, 0xc0000339c0)
	/Users/phil/work/zed/pkg/signalctx/signalctx.go:25 +0xad
created by github.com/brimdata/zed/pkg/signalctx.New
	/Users/phil/work/zed/pkg/signalctx/signalctx.go:24 +0x12f

goroutine 50 [chan send]:
github.com/brimdata/zed/driver.run.func2(0x276cd10, 0xc00032e700, 0xc0004c63c0, 0xc0004c6420)
	/Users/phil/work/zed/driver/driver.go:129 +0x48
created by github.com/brimdata/zed/driver.run
	/Users/phil/work/zed/driver/driver.go:114 +0x195

rax    0x104
rbx    0xf901e00
rcx    0x7ffeefbff528
rdx    0x300
rdi    0x1e29420
rsi    0x30100000400
rbp    0x7ffeefbff5d0
rsp    0x7ffeefbff528
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x1e293e0
r13    0x16
r14    0x30100000400
r15    0x300
rip    0x7fff203accde
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
```

**Comment by philrz** [comment]
Verified in Zed commit bbc92a4.

Repeating the repro steps, there's no longer a hang.

```
~/work/zed-sample-data/zng$ zq -version
Version: v0.29.0-462-gbbc92a45

~/work/zed-sample-data/zng$ zq * > /tmp/results.zng

~/work/zed-sample-data/zng$ zq -f csv /tmp/results.zng
_path,ts,ts_delta,peer,gaps,acks,percent_lost
capture_loss,2018-03-24T17:30:20.600852Z,900.000127,zeek,1400,1414346,0.098986
capture_loss,2018-03-24T17:36:30.158766Z,369.557914,zeek,919,663314,0.138547
CSV output requires uniform records but multiple types encountered (consider 'fuse')
```

Thanks @nwt!
