### ISSUE TITLE
complex cast syntax

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3327]
```
< complex-type >(val) 
```
should be shorthand for 
```
cast(val, <complex-type>)
```
To be consistent with the casting syntax.

Right now we get a panic
```
echo "{s:1}" | zq "this:=<{s:string}>(this)" -
panic: reflect.Set: value of type *zed.TypeValue is not assignable to type zed.Type

goroutine 1 [running]:
reflect.Value.assignTo(0x17f0e40, 0xc0003b6320, 0x16, 0x18bbf74, 0xb, 0x17e6280, 0xc0003d2140, 0xc0003ba6c0, 0xc0003d05a0, 0x1)
	/usr/local/go/src/reflect/value.go:2451 +0x3f7
reflect.Value.Set(0x17e6280, 0xc0003d2140, 0x194, 0x17f0e40, 0xc0003b6320, 0x16)
	/usr/local/go/src/reflect/value.go:1564 +0xbd
github.com/brimdata/zed/pkg/unpack.convertStruct(0x17c55e0, 0xc0003d2120, 0x16, 0xc0003b9fb0, 0x16, 0x0)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:230 +0x330
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x17d1ac0, 0xc0003b9e00, 0xc00021f358, 0x11085c6, 0xc00039de94, 0xc)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:151 +0x167
github.com/brimdata/zed/pkg/unpack.Reflector.unpackObject(0xc0002a6c00, 0xc0003b9da0, 0x10, 0x9a03f78, 0x10)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:172 +0xe5
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x17d1ac0, 0xc0003b9da0, 0xc0003ba5d0, 0xc0003b9d40, 0x15, 0x17d1ac0)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:140 +0x8d
github.com/brimdata/zed/pkg/unpack.Reflector.unpackArray(0xc0002a6c00, 0xc0003ba580, 0x1, 0x1, 0xc0003b9f50, 0x10000c000342160, 0xffffffffffffffff, 0x0, 0xc00021f540)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:184 +0xc5
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x179c200, 0xc00031bbf0, 0xc0003ba4c0, 0x17c03c0, 0xc0003ba4c0, 0x94)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:164 +0x338
github.com/brimdata/zed/pkg/unpack.Reflector.unpackObject(0xc0002a6c00, 0xc0003b9d70, 0x179c200, 0x9a03f78, 0x10)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:172 +0xe5
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x17d1ac0, 0xc0003b9d70, 0xc0003ba5c0, 0x17c03c0, 0xc00021f790, 0x100f0bb)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:140 +0x8d
github.com/brimdata/zed/pkg/unpack.Reflector.unpackArray(0xc0002a6c00, 0xc0003ba5a0, 0x1, 0x1, 0x0, 0xc00021f7f8, 0x1015b6b, 0x110, 0x1844a20)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:184 +0xc5
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x179c200, 0xc00031bc08, 0x4, 0xc0003d0508, 0x0, 0x0)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:164 +0x338
github.com/brimdata/zed/pkg/unpack.Reflector.unpackObject(0xc0002a6c00, 0xc0003b9d40, 0x1, 0x9a03f78, 0x10)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:172 +0xe5
github.com/brimdata/zed/pkg/unpack.Reflector.unpack(0xc0002a6c00, 0x17d1ac0, 0xc0003b9d40, 0x178fd60, 0xc0003ba4c0, 0x0, 0x0)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:140 +0x8d
github.com/brimdata/zed/pkg/unpack.Reflector.Unmarshal(0xc0002a6c00, 0xc0003cc000, 0x122, 0x140, 0x140, 0x0, 0x0, 0x0)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:83 +0x16f
github.com/brimdata/zed/pkg/unpack.Reflector.UnmarshalObject(0xc0002a6c00, 0x17d1ac0, 0xc0003b9470, 0x0, 0x1, 0x1, 0xc000326000)
	/Users/mccanne/repo/zed/pkg/unpack/reflector.go:101 +0x96
github.com/brimdata/zed/compiler/ast.UnpackMapAsProc(0x17d1ac0, 0xc0003b9470, 0x0, 0xc000324000, 0x18, 0x17d1ac0)
	/Users/mccanne/repo/zed/compiler/ast/unpack.go:108 +0x45
github.com/brimdata/zed/compiler.ParseProc(0x7ffeefbffa63, 0x18, 0x0, 0x0, 0x0, 0x1826900, 0xc00031a000, 0xc00007fd20, 0x2)
	/Users/mccanne/repo/zed/compiler/compiler.go:167 +0xa6
github.com/brimdata/zed/cmd/zed/query.ParseSourcesAndInputs(0xc0000321d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00031a000, 0x0, 0x0, 0x40, ...)
	/Users/mccanne/repo/zed/cmd/zed/query/command.go:127 +0x18f
main.(*Command).Run(0xc0000f3080, 0xc0000321c0, 0x2, 0x2, 0x0, 0x0)
	/Users/mccanne/repo/zed/cmd/zq/main.go:113 +0x1bb
github.com/brimdata/zed/pkg/charm.path.run(0xc0000100d8, 0x1, 0x1, 0xc0000321c0, 0x2, 0x2, 0xc0000100d8, 0x1)
	/Users/mccanne/repo/zed/pkg/charm/path.go:11 +0x8f
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x1e23f00, 0xc0000321c0, 0x2, 0x2, 0xc00021ff78, 0x1007865)
	/Users/mccanne/repo/zed/pkg/charm/charm.go:63 +0x1e7
main.main()
	/Users/mccanne/repo/zed/cmd/zq/main.go:151 +0x85
```

**Comment by mccanne** [comment]
Also, this should work...
```
echo "{a:[1,2,3]}" | zq "x:=cast(a,<[string]>)" -
{a:[1,2,3],x:"shaper function type argument is not a record type: \"[string]\""(error)}
```
even though this works:
```
echo "{a:[1,2,3]}" | zq "x:=cast(this,<{a:[string]}>)" -
{a:[1,2,3],x:{a:["1","2","3"]}}
```
