### ISSUE TITLE
fuse crash on union

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3399]
```
% cat in.zson
{a:1}(({a:int64},{b:int64}))
{b:2}(({a:int64},{b:int64}))
% zq fuse in.zson
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11e9817]

goroutine 53 [running]:
github.com/brimdata/zed/expr/agg.(*Schema).Mixin(0xc00039c700, 0x0, 0x1a26540, 0xc00039ca60)
	/Users/mccanne/repo/zed/expr/agg/schema.go:22 +0x37
github.com/brimdata/zed/proc/fuse.(*Fuser).Write(0xc0003b6780, 0xc000430000, 0x2, 0x64)
	/Users/mccanne/repo/zed/proc/fuse/fuser.go:55 +0x147
github.com/brimdata/zed/zbuf.WriteBatch(0x1a178a0, 0xc0003b6780, 0x1a26850, 0xc000392540, 0x0, 0x0)
	/Users/mccanne/repo/zed/zbuf/batch.go:39 +0x8b
github.com/brimdata/zed/proc/fuse.(*Proc).pullInput(0xc0003b0700, 0x0, 0x0)
	/Users/mccanne/repo/zed/proc/fuse/fuse.go:59 +0xd7
github.com/brimdata/zed/proc/fuse.(*Proc).run(0xc0003b0700)
	/Users/mccanne/repo/zed/proc/fuse/fuse.go:40 +0x2b
created by github.com/brimdata/zed/proc/fuse.(*Proc).Pull.func1
	/Users/mccanne/repo/zed/proc/fuse/fuse.go:32 +0x3e

```

**Comment by mccanne** [comment]
This has been fixed.
