### ISSUE TITLE
"panic: bad uvarint: 0" during flatten()

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4058]
Repro is with Zed commit 2d52400. We stumbled onto this issue while working on possible solutions for #4050.

```
$ zq -version
Version: v1.2.0-29-g2d52400f

$ zq -Z before.zson 
{
    value: {
        before: null (foo={bar:int32})
    }
}

$ zq -Z 'flatten(this)' before.zson
panic: bad uvarint: 0
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x16a32a0, 0xc0003d4810})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x212
github.com/brimdata/zed/zcode.(*Iter).Next(0x2000000203000?)
	/Users/phil/work/zed/zcode/iter.go:26 +0x219
github.com/brimdata/zed/runtime/expr/function.(*Flatten).encode(0xc00004b200, {0xc0002d6a00?, 0x1, 0x16ea2c0?}, {0x193dc90?, 0xc0003ea330?}, {0xc0002d6aa0, 0x2, 0x2}, {0x0, ...})
	/Users/phil/work/zed/runtime/expr/function/flatten.go:89 +0x125
github.com/brimdata/zed/runtime/expr/function.(*Flatten).encode(0xc00004b200, {0xc0002d6a40?, 0x1, 0x10229a7?}, {0x193dc90?, 0xc0003ea330?}, {0xc0003d4800, 0x1, 0x1}, {0xc0002cf6d3, ...})
	/Users/phil/work/zed/runtime/expr/function/flatten.go:92 +0x2c8
github.com/brimdata/zed/runtime/expr/function.(*Flatten).encode(0xc00004b200, {0xc0002d6a80?, 0x1, 0x100b615?}, {0x193dc90?, 0xc0003ea330?}, {0xc00019f848, 0x0, 0x0}, {0xc0002cf6d2, ...})
	/Users/phil/work/zed/runtime/expr/function/flatten.go:92 +0x2c8
github.com/brimdata/zed/runtime/expr/function.(*Flatten).Call(0xc00004b200, {0x800e750, 0xc000013d40}, {0xc0002e5cb0, 0x1, 0x800e720?})
	/Users/phil/work/zed/runtime/expr/function/flatten.go:47 +0x230
github.com/brimdata/zed/runtime/expr.(*Call).Eval(0xc00007ed20, {0x800e720?, 0xc000013d40}, 0x8008648?)
	/Users/phil/work/zed/runtime/expr/eval.go:809 +0x84
github.com/brimdata/zed/runtime/op/yield.(*Proc).Pull(0xc0002e5ce0, 0x5?)
	/Users/phil/work/zed/runtime/op/yield/yield.go:31 +0x413
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc000013c98, 0x80)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0x19405c0?, 0x50?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x800e570?, 0x40?)
	/Users/phil/work/zed/runtime/query.go:92 +0x45
github.com/brimdata/zed/zbuf.CopyPuller({0x800e570, 0xc000013758}, {0x1938600, 0xc0002d6760})
	/Users/phil/work/zed/zbuf/batch.go:106 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc00026a000, {0xc0000d2020, 0x2, 0x2})
	/Users/phil/work/zed/cli/zq/command.go:166 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc0000c80a8?, 0x1, 0x1}, {0xc0000d2020?, 0x2, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc0000d2010, 0x3, 0x3})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

It looks like it's choking on the named type, as I can't repro if it's a simple `null` or `null (string)`.

**Comment by philrz** [comment]
Verified in Zed commit c5e14d0.

Now the example record is flattened without crashing.

```
$ zq -version
Version: v1.2.0-32-gc5e14d08

$ zq -Z 'flatten(this)' before.zson
[
    {
        key: [
            "value",
            "before"
        ],
        value: null (foo={bar:int32})
    }
]
```

I've also used this fixed version to run the more complex Zed from #4050 against the community user's original repro data which can't be shared publicly due to sensitivity. However, it does complete successfully.

```
$ zq -Z 'over flatten(value.after) => ( value:=grep(*date*)?time(value*1ms):value | collect(this) | unflatten(collect) )' results.zng
{
...
}

$ echo $?
0
```

Thanks @mattnibs!
