### ISSUE TITLE
zng decoder crash on bad data

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#4082]
The zng decoder crashes ungracefully with a certain bad input created as a zst file.  It should detect the problem and report an error.

Repro is at Zed commit 520b145 with this `t.zson`...
```
{a:[1,2],b:[]([int64])}
{a:null([int64]),b:[1,2,3]}
```
Make a zst file from it then run zq on the zst as if it were zng either via autodetection or with `-i zng`...
```
$ zq -version
Version: v1.2.0-48-g520b145a

$ zq -f zst -o t.zst t.zson
$ zq -i zng t.zst

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1150c15]

goroutine 60 [running]:
github.com/brimdata/zed.appendTypeValue({0xc0003dc740, 0x1, 0x40}, {0x0?, 0x0?}, 0x0?)
	/Users/mccanne/repo/zed/type.go:536 +0x515
github.com/brimdata/zed.appendTypeValue({0xc0003dc740, 0x0, 0x40}, {0x1921c50?, 0xc000392990?}, 0xc000404c88)
	/Users/mccanne/repo/zed/type.go:515 +0x227
...
```

**Comment by philrz** [comment]
Verified in Zed commit 6737ae9.

Now instead of a panic, we get an error message.

```
$ zq -version
Version: v1.2.0-61-g6737ae9f

$ zq -f zst -o t.zst t.zson

$ zq -i zng t.zst
t.zst: primitive type ID 4 not implemented
```

Thanks @nwt!
