### ISSUE TITLE
nil pointer dereference during compaction

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4177]
Repro is with Zed commit f5350b0.

I've only been able to reproduce this issue by having some records that lack the pool key mixed in with the ones that do. Steps:

1. Start a `zed serve`

```
$ zed -version
Version: v1.2.0-102-gf5350b0c

$ rm -rf lake && zed serve -lake lake -log.level debug
{"level":"info","ts":1667508957.307296,"msg":"Open files limit raised","limit":61440}
...
```

2. Create a pool with small object size.

```
$ zed create -S 10KB zeek
pool created: zeek 2H3KUgq5lEO5udUEeoqeieLVnc3
```

3. Start a `zed monitor manage` with intent to compact data as it accumulates. I notice that HTTP 500 error at startup, but that symptom looks similar to existing issue #3029 and I'm guessing is unrelated.

```
$ cat manage.yaml 
coldthresh: 0s

$ zed manage monitor -config manage.yaml
{"level":"error","ts":1667508346.559808,"logger":"pool","msg":"scan error","name":"zeek","id":"2H3KUgq5lEO5udUEeoqeieLVnc3","branch":"main","error":"status code 500: unknown pool metadata type: \"objects\"","stacktrace":"github.com/brimdata/zed/cmd/zed/manage/lakemanage.(*poolMonitor).run.func1\n\t/Users/phil/work/zed/cmd/zed/manage/lakemanage/monitor.go:169"}
...
```

4. Unpack the attached [data.tgz](https://github.com/brimdata/zed/files/9932874/data.tgz) and load using the following loop. As you can see, there's one `ts`-free record loaded after each 100 of the regular `conn` records.

```
$ tar xvf data.tgz
$ NUM="1" ; while [ "$NUM" -le 100 ]; do zed load $NUM.zson; NUM=$(expr $NUM + 1); done; echo '{"_path":"loaded_scripts","_write_ts":"1970-01-01T00:00:00.000000Z","name":"/usr/local/zeek-5.0.2/share/zeek/base/init-bare.zeek"}' | zed load -
```

It seems that if I repeat that looped load three times in a row, consistently on the third time through, the `zed manage monitor` dies with the following stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x165aa83]

goroutine 3382 [running]:
github.com/brimdata/zed/runtime/expr/extent.(*Generic).Overlaps(0x0, 0xc000193620?, 0xc000324ba0?)
	/Users/phil/work/zed/runtime/expr/extent/span.go:90 +0x23
github.com/brimdata/zed/cmd/zed/manage/lakemanage.(*Run).SizeUncoveredBy(0xc0000fecb8?, {0x1d824e0, 0x0})
	/Users/phil/work/zed/cmd/zed/manage/lakemanage/run.go:41 +0x7b
github.com/brimdata/zed/cmd/zed/manage/lakemanage.Scan.func1({{0x1d824e0, 0xc000388d20}, 0xc00007bfe0, {0xc0002807a0, 0x2, 0x2}}, {0x1d824e0?, 0x0?})
	/Users/phil/work/zed/cmd/zed/manage/lakemanage/scan.go:27 +0xa7
github.com/brimdata/zed/cmd/zed/manage/lakemanage.Scan({0x1d7d1f0?, 0xc0000f4600?}, {0x1d716c0, 0xc0000b8510}, 0xc0000d41e0, 0x0, 0xc00015e5b0?)
	/Users/phil/work/zed/cmd/zed/manage/lakemanage/scan.go:68 +0x453
github.com/brimdata/zed/cmd/zed/manage/lakemanage.(*poolMonitor).scan.func1()
	/Users/phil/work/zed/cmd/zed/manage/lakemanage/monitor.go:193 +0x57
created by github.com/brimdata/zed/cmd/zed/manage/lakemanage.(*poolMonitor).scan
	/Users/phil/work/zed/cmd/zed/manage/lakemanage/monitor.go:192 +0x212
```

**Comment by philrz** [comment]
Update: I've verified that, as expected, the fix in #3029 fixes the HTTP 500 error shown above go away when we start `zed manage monitor`.

The panic still reproduces, though.

**Comment by philrz** [comment]
Verified in Zed commit 3414ad9.

Since the original repro, I wrote a simple new tool https://github.com/brimdata/zed-perf-testing/tree/main/record-poster that posts synthetic records in a manner similar to the repro above. In multiple commits leading up to 3414ad9 I could run the tool as described in its README example and consistently repro the crash in just over 1 minute. Now at Zed commit 3414ad9 that has the benefit of the fix, it's been running continuously for 15+ minutes without a problem, so the issue does indeed appear to be fixed.

Thanks @mattnibs!
