### ISSUE TITLE
panic: unwait called without all parents blocked

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4318]
Repro is with Zed commit 7de3ffa.

This bug appears to be a side effect of some of the Zed appended by the app in https://github.com/brimdata/brim/pull/2355 to help with pagination.

To repro, start a Zed service:

```
$ zed -version
Version: v1.4.0-16-g7de3ffa1

$ rm -rf lake

$ zed -lake lake serve
{"level":"info","ts":1673975387.540253,"logger":"core","msg":"Started"}
...
```

Create a pool, load the HTTP [zed-sample-data](https://github.com/brimdata/zed-sample-data), and execute the query shown.

```
$ zed create http
pool created: http 2KSkbbmNVx4r1eMBgcWFmTx1np0

$ zed -use http load http.log.gz 
(1/1) 5.52MB/5.52MB 5.52MB/s 100.00%
2KSkc0Li8a4zMx3NkHgXcxzAObb committed

$ zed query 'from "http" | _path=="http" | method !=null | count() by ts:=bucket(ts,20ms),method | { i: count(), v: this} | i > 0 | head 2000'
{i:1(uint64),v:{ts:2018-03-24T17:36:30Z,method:"POST",count:20(uint64)}}
{i:2(uint64),v:{ts:2018-03-24T17:36:29.98Z,method:"GET",count:1(uint64)}}
...
```

At this point the Zed service crashes with the following panic:

```
panic: unwait called without all parents blocked

goroutine 110 [running]:
github.com/brimdata/zed/runtime/op/combine.(*Proc).unwait(0x1?)
	/Users/phil/work/zed/runtime/op/combine/combine.go:89 +0x13d
github.com/brimdata/zed/runtime/op/combine.(*Proc).propagateDone(0xc0005444b0)
	/Users/phil/work/zed/runtime/op/combine/combine.go:154 +0x14e
github.com/brimdata/zed/runtime/op/combine.(*Proc).Pull(0xc0005444b0, 0x44?)
	/Users/phil/work/zed/runtime/op/combine/combine.go:44 +0x7f
github.com/brimdata/zed/runtime/op/groupby.(*Proc).sendResult(0xc0005445a0, {0x2259060, 0xc002237f50}, {0x0, 0x0})
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:265 +0x162
github.com/brimdata/zed/runtime/op/groupby.(*Proc).run(0xc0005445a0)
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:245 +0x42f
created by github.com/brimdata/zed/runtime/op/groupby.(*Proc).Pull.func1
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:168 +0x6d
```

If I remove the `head 2000` from the end of the Zed pipeline, though, it doesn't crash.

**Comment by philrz** [comment]
Verified in Zed commit 3ca4b8a.

As shown in the attached video, now we can repeat the repro steps and execute the `zed query` with the `head 2000` repeatedly and never see a crash in the Zed service.

https://user-images.githubusercontent.com/5934157/214997524-777fa25f-8d13-48a5-83e4-c94257309a8b.mp4

Thanks @nwt!
