### ISSUE TITLE
Can't read with "file" from inside User Op

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4645]
Repro is with Zed commit 90db56f.

The following works ok without User Ops.

```
$ zq -version
Version: v1.8.1-27-g90db56f9

$ cat file_main.zed
file sample.zng | count()

$ zq -I file_main.zed
31(uint64)
```

However, if I try to move the logic to inside a User Op, now it won't get past the CLI tooling.

```
$ cat file_in_op.zed
op CallMe(): (
  file sample.zng | count()
)
CallMe()

$ zq -I file_in_op.zed
no input specified: use a command-line file or a Zed source operator
```

---

Incidentally, while working my way up to that repro, at one point I had this variation with a parameter that caused a panic.

```
$ cat file_in_op_with_param.zed
op CallMe(const param): (
  file sample.zng | count()
)
CallMe("goodbye")

$ echo "null" | zq -I file_in_op_with_param.zed -
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x22a5ca0, 0xc0000ec420})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed/runtime/op.(*exitScope).Pull(0xc0000be078, 0x5?)
	/Users/phil/work/zed/runtime/op/scope.go:46 +0x10e
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc0000be408, 0x80)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0xc0004b8020?, 0x60?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x2b7a8360?, 0x30?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x2b7a8360, 0xc0008222e8}, {0x25c1460, 0xc000120cc0})
	/Users/phil/work/zed/zbuf/batch.go:165 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc000124380, {0xc00003e0b0, 0x1, 0x1})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc0000a8278?, 0x1, 0x1}, {0xc00003e0b0?, 0x1, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc00003e090, 0x3, 0x3})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

It looks like I triggered what may be the same stack dump when attempting the [self `join` example from the tutorial](https://zed.brimdata.io/docs/next/tutorials/join#self-joins).

```
$ zq -version
Version: v1.8.1-28-g23140538

$ cat inner-join-streamed-in-op-with-params.zedop do_join(const left_match, const right_match, ...): (
  switch (
    case has(this[left_match]) => sort flavor
    case has(this[right_match]) => sort likes
  ) | inner join on flavor=likes eater:=name
)
do_join("color", "age", this)

$ cat fruit.ndjson people.ndjson | zq -z -I inner-join-streamed-in-op-with-params.zed -
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x22a5be0, 0xc0000c21b0})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed/runtime/op.(*exitScope).Pull(0xc000932078, 0x5?)
	/Users/phil/work/zed/runtime/op/scope.go:46 +0x10e
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc000932090, 0xc0)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0xc0004ba020?, 0x70?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x2c9d4508?, 0x30?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x2c9d4508, 0xc000932438}, {0x25c1340, 0xc0009b8780})
	/Users/phil/work/zed/zbuf/batch.go:165 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc00002e380, {0xc0000ce040, 0x1, 0x1})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc0000c4298?, 0x1, 0x1}, {0xc0000ce040?, 0x1, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc0000ce010, 0x4, 0x4})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

**Comment by philrz** [comment]
Verified in Zed commit 7ba4ecc.

Repeating the original repro steps, now I can make the filename reference from inside the User Op. Syntax has been otherwise updated to be current (i.e., `const` is no longer specified as part of the parameter definitions).

```
$ zq -version
Version: v1.8.1-59-g7ba4ecc6

$ cat file_in_op.zed
op CallMe(): (
  file sample.zng | count()
)
CallMe()

$ zq -I file_in_op.zed
31(uint64)
```

Incidentally, with the dropping of `const` from the definition of parameters, the stack trace no longer occurs and instead we see the error message tracked in separate issue #4701.

```
$ cat file_in_op_with_param.zed
op CallMe(param): (
  file sample.zng | count()
)
CallMe("goodbye")

$ echo "null" | zq -I file_in_op_with_param.zed -
redundant inputs specified: use either command-line files or a Zed source operator
```

Both #4701 and #4700 remain as open issues to track loose ends that were identified during the testing of linked PR #4698 which affect variations on this use case.

Thanks @mattnibs!
