### ISSUE TITLE
panic: duplicate field: "this"

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4715]
Repro is with Zed commit e6be73e and attached [data.csv.gz](https://github.com/brimdata/zed/files/12062983/data.csv.gz).

```
$ zq -version
Version: v1.8.1-64-ge6be73ee

$ echo '"foo"' | zq -z 'yield {this,this}' -
panic: duplicate field: "this"
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x21254c0, 0xc0004ec8e0})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed.(*Context).MustLookupTypeRecord(...)
	/Users/phil/work/zed/context.go:154
github.com/brimdata/zed/runtime/expr.(*recordExpr).Eval(0xc0004d05a0, {0x25c9f10, 0xc0004cf6a8}, 0x100db27?)
	/Users/phil/work/zed/runtime/expr/values.go:59 +0x37a
github.com/brimdata/zed/runtime/op/yield.(*Op).Pull(0xc0004cf680, 0x5?)
	/Users/phil/work/zed/runtime/op/yield/yield.go:33 +0x46e
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc0004aea20, 0xa0)
	/Users/phil/work/zed/runtime/op/mux.go:133 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0xc0004ac020?, 0x80?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x2c902b50?, 0x30?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x2c902b50, 0xc0004ae870}, {0x25b9520, 0xc0004fcb10})
	/Users/phil/work/zed/zbuf/batch.go:162 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc000032380, {0xc00003e0a0, 0x2, 0x2})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc000794270?, 0x1, 0x1}, {0xc00003e0a0?, 0x2, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc00003e090, 0x3, 0x3})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

**Comment by philrz** [comment]
Oops. I see this is a duplicate of #4440. Closing.
