### ISSUE TITLE
Python client load failure to pool with "/" in its name

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4814]
Repro is with the Python client at Zed commit c29dd97 and Zed service at commit c84f111. This symptom was first reported in a [community Slack thread](https://brimdata.slack.com/archives/CTSMAK6G7/p1698084701997969).

Start from the following Python `test.py`.

```
#!/usr/bin/env python3

import zed
import json

POOL1 = "test"
POOL2 = "test/new"

client = zed.Client("http://localhost:9988")
client.create_pool(POOL1)
client.create_pool(POOL2)
x = {'test':'yup','bucket':'hat'}
client.load(POOL2,json.dumps(x))
```

With Zui Insiders 1.3.2-1 launched (which starts a Zed service at commit c84f111) it fails.

```
$ pip3 freeze | grep -i zed
zed @ git+https://github.com/brimdata/zed@c29dd976276c66f5994b79e92155b54e8ad6ad20#subdirectory=python/zed

$ curl http://localhost:9988/version
{"version":"v1.10.0-13-gc84f1112"}

$ python3 test.py 
Traceback (most recent call last):
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/zed.py", line 72, in __raise_for_status
    error = response.json()['error']
            ^^^^^^^^^^^^^^^
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/phil/work/jason/2023-10-23-python/test.py", line 13, in <module>
    client.load(POOL2,json.dumps(x))
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/zed.py", line 55, in load
    self.__raise_for_status(r)
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/zed.py", line 74, in __raise_for_status
    response.raise_for_status()
  File "/Users/phil/work/jason/2023-10-23-python/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:9988/pool/test/new/branch/main
```

If the name of `POOL2` is changed to no longer contain a `/` (e.g., use a `.` instead) it works. Therefore we assume the problem is related to the `/` in the pool name being treated as part of the URL being hit on the lake API.

**Comment by philrz** [comment]
Verified in Zed commit 9eb315c.

Starting with an empty lake service running on port `9867` and the `test.py` modified to access the lake there, we see the pool with the `/` in its name is now created without compaint.

```
$ zed -version
Version: v1.13.0-9-g9eb315c9

$ pip3 freeze | grep -i zed
zed @ git+https://github.com/brimdata/zed@9eb315c9c100ba58666fefc87380f39a8a6ae76b#subdirectory=python/zed

$ python3 test.py

$ zed ls
test 2c3KXTA9BUi1udDc2mhcTRRRwk9 key ts order desc
test/new 2c3KXUYqNrM0tZXwmhxr8W119bT key ts order desc
```

Thanks @mattnibs!
