### ISSUE TITLE
Panic when using "over" in an expression context

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#5077]
Repro is with Zed commit f1be6a4.

@mattnibs and I were working toward responding to a community user's inquiry in a [Slack thread](https://brimdata.slack.com/archives/CTT24051C/p1710456812385789). I'd gotten to the point where I had this working in a user-defined operator:

```
$ cat op.zed 
op MyFlatten(val): (
  yield (over val | over this | collect(this))

$ zq -version
Version: v1.14.0-17-gf1be6a4a

$ echo '[[1,2],[3,4]]' | zq -I op.zed 'MyFlatten(this)' -
[1,2,3,4]
```

So I thought to try the equivalent in a user-defined function, which triggered this panic.

```
$ cat func.zed 
func MyFlatten(val): (
  (over val | over this | collect(this))
)

$ echo '[[1,2],[3,4]]' | zq -I func.zed 'yield MyFlatten(this)' -
panic: runtime error: index out of range [0] with length 0

goroutine 53 [running]:
github.com/brimdata/zed/runtime/sam/expr.Var.Eval(...)
	/Users/phil/work/zed/runtime/sam/expr/var.go:14
github.com/brimdata/zed/runtime/sam/op/traverse.(*Over).over(0xc0003e3da0, {0x28d5478?, 0xc000789f50}, {{0x28c76d0?, 0x36de9e0?}, 0x0?, 0x0?})
	/Users/phil/work/zed/runtime/sam/op/traverse/over.go:72 +0x164
github.com/brimdata/zed/runtime/sam/op/traverse.(*Over).Pull(0xc0003e3da0, 0xc0?)
	/Users/phil/work/zed/runtime/sam/op/traverse/over.go:56 +0x1a9
github.com/brimdata/zed/runtime/sam/op/traverse.(*Scope).run(0xc0006d1c70)
	/Users/phil/work/zed/runtime/sam/op/traverse/scope.go:69 +0x37
created by github.com/brimdata/zed/runtime/sam/op/traverse.(*Scope).Pull.func1 in goroutine 52
	/Users/phil/work/zed/runtime/sam/op/traverse/scope.go:47 +0x56
```

Meanwhile @mattnibs was coming up with a more sophisticated variant that was closer to the user's original intent, and it looks like he hit a similar panic.

```
$ cat maybe_flatten.zed
func maybe_flatten_fn(a): (
   kind(a) == "array"  
     ? (over a | and(kind(this) == "array")) 
        ? "It's an array of arrays, so I would flatten"
        : "It's an array containing some non-array values, so I would not flatten"
     : "It's not even an array, so I ain't touchin' that"
)

yield [[1,2],[3,4]], "hello"
| yield maybe_flatten_fn(this)

$ echo null | zq -I maybe_flatten.zed -
panic: runtime error: index out of range [0] with length 0

goroutine 25 [running]:
github.com/brimdata/zed/runtime/sam/expr.Var.Eval(...)
	/Users/phil/work/zed/runtime/sam/expr/var.go:14
github.com/brimdata/zed/runtime/sam/op/traverse.(*Over).over(0xc00056e840, {0x28d5478?, 0xc000876e10}, {{0x28c76d0?, 0x36de9e0?}, 0x0?, 0x0?})
	/Users/phil/work/zed/runtime/sam/op/traverse/over.go:72 +0x164
github.com/brimdata/zed/runtime/sam/op/traverse.(*Over).Pull(0xc00056e840, 0x0?)
	/Users/phil/work/zed/runtime/sam/op/traverse/over.go:56 +0x1a9
github.com/brimdata/zed/runtime/sam/op/traverse.(*Scope).run(0xc0006788c0)
	/Users/phil/work/zed/runtime/sam/op/traverse/scope.go:69 +0x37
created by github.com/brimdata/zed/runtime/sam/op/traverse.(*Scope).Pull.func1 in goroutine 24
	/Users/phil/work/zed/runtime/sam/op/traverse/scope.go:47 +0x56
```

As a side-effect of working on this, we also both recognized that this functionality should be mentioned in the [expressions docs](https://zed.brimdata.io/docs/language/expressions), but we might as well fix the bug before calling more attention to it.

**Comment by philrz** [comment]
Verified in Zed commit 3e5febe.

Both of the programs shown above that previously caused a panic now run successfully.

```
$ zq -version
Version: v1.14.0-21-g3e5febe7

$ echo '[[1,2],[3,4]]' | zq -I func.zed 'yield MyFlatten(this)' -
[1,2,3,4]

$ echo null | zq -I maybe_flatten.zed -
"It's an array of arrays, so I would flatten"
"It's not even an array, so I ain't touchin' that"
```

Thanks @mattnibs!
